###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  - id: "wikipediaplus"
    name: Wikipedia+
    type:
      - browser-extension
      - chrome-extension
      - firefox-extension
      - edge-extension
      - safari-extension
      - chromium-extension
      - brave-extension
      - opera-extension
      - operagx-extension
      - yandex-extension
    version: "{{package.version}}"
    description: "{{package.description}}"
    homepage: "{{package.homepage}}"
    status: "active"
    repo: "https://github.com/pigeonposse/wikipediaplus"
    logo: "https://raw.githubusercontent.com/pigeonposse/wikipediaplus/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/wikipediaplus/main/docs/banner.png"
    download: 
      - name: "Chrome Web Store"
        url:  "https://chromewebstore.google.com/detail/wikipedia-+/nnkleafalbcmeamobndfmcjhphipnnaj"
      - name: "Edge Web Store"
        url: ""
      - name: "Firefox Mozilla Store"
        url: "https://addons.mozilla.org/es/firefox/addon/wikipediaplus/"
      - name: "Chrome Extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-chrome.zip"
      - name: "Chrome Extension (Manifest 2)"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-chrome-mv2.zip"
      - name: "Edge extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-edge.zip"
      - name: "Edge Extension (Manifest 2)"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-edge-mv2.zip"
      - name: "Firefox extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-firefox.zip"
      - name: "Safari Extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-safari.tar.gz"
      - name: "Brave Extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-brave.zip"
      - name: "Opera Extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-opera.zip"
      - name: "Opera GX Extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-opera-gx.zip"
      - name: "Vivaldi Extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-vivaldi.zip"
      - name: "Yandex extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-yandex.zip"
      - name: "Yandex Extension (Manifest 2)"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-yandex-mv2.zip"
      - name: "Chromium Extension"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-chromium.zip"
      - name: "Chromium Extension (Manifest 2)"
        url: "https://github.com/pigeonposse/wikipediaplus/releases/latest/download/wikipediaplus-chromium-mv2.zip"
