###############################################################################
# RELEASE EXTENSIONS
###############################################################################

name: 🚀🧩 Release extensions


###############################################################################
# ON
###############################################################################

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Set number for release version'
        type: string
        required: true

###############################################################################
# JOBS
###############################################################################

jobs:
  release_exts:
    name: 🚀🧩 Release extensions
    # for the Safari build. If set to 'macos-13-xlarge' or 'macos-latest' safari build it will not be compatible with macos Intel processor
    # @see https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: macos-13
    permissions:
      contents: write
    steps:

      #########################################################################
      # INIT
      #########################################################################

      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: ⬇️🟢 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ⬇️🥡 Install pnpm
        uses: pnpm/action-setup@v3

      - name: ⬇️📦 Install dependencies
        run: |
          pnpm install --no-frozen-lockfile


      #########################################################################
      # BUILD PKG
      #########################################################################

      - name: 🏗 Build
        run: pnpm build


      #########################################################################
      # GET PKG INFO
      #########################################################################

      - name: 📦📄 Get package.json data
        id: pkg
        run: |
          echo "description=$(jq -r '.description' ./package.json)" >> $GITHUB_OUTPUT
          echo "name=$(jq -r '.name' ./package.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r '.version' ./package.json)" >> $GITHUB_OUTPUT 


      #########################################################################
      # GITHUB RELEASE
      #########################################################################

      - name: 🧩🗂️ Create Github release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.pkg.outputs.version }}"
          name: '${{ steps.pkg.outputs.version }}'
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: "dist/exts/*"
          body: |
            <p><b> ${{ steps.pkg.outputs.name }} v${{ steps.pkg.outputs.version }}</b></p>
            <p>${{ steps.pkg.outputs.description }}</p>

            🧩 [CHANGELOG]( https://github.com/pigeonposse/wikipediaplus/blob/main/CHANGELOG.md)
            📜 [LICENSE](https://github.com/pigeonposse/wikipediaplus/blob/main/LICENSE)
            🔏 [PRIVACY](https://github.com/pigeonposse/wikipediaplus/blob/main/POLICY.md)


      #########################################################################
      # FIREFOX
      #########################################################################

      - name: 🧩🦊 Upload FIREFOX extension
        uses: trmcnvn/firefox-addon@v1
        with:
          # uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
          uuid: '{a2e191e8-b8eb-490b-b282-9f3d2c0332bf}'
          xpi: dist/comp/firefox-${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}.zip
          manifest: dist/firefox/manifest.json
          # get keys in:
          # https://addons.mozilla.org/en-US/developers/addon/api/key/
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
        continue-on-error: true


############################################################################### 
